### ISSUE TITLE
Ambiguous error when Hadoop and hbase conf files can't be found

### ISSUE THREAD

**Issue by raphaelhamonnais** [Finaxys/hadoop-tutorial#2]
The conf files for hadoop and hbase must bu specified in the properties.txt file located at the project root.
The path for this conf files is specific to the user environnement : it depends on where and how you've installed hbase and hadoop.

The problem is that the error generated is ambiguous.
This is an example of the error generated : 

```
16/07/11 15:36:54 ERROR conf.Configuration: error parsing conf file:/tmp/configuration.xml
java.io.FileNotFoundException: /tmp/configuration.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2468)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2536)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2502)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:981)
	at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:1031)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2189)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2219)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:43)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at fr.finaxys.tutorials.utils.hbase.AtomHBaseHelper.openTable(AtomHBaseHelper.java:316)
	at fr.finaxys.tutorials.utils.hbase.SimpleHBaseInjector.createOutput(SimpleHBaseInjector.java:58)
	at fr.finaxys.tutorials.utils.AtomLogger.init(AtomLogger.java:36)
	at fr.finaxys.tutorials.utils.AtomLogger.<init>(AtomLogger.java:28)
	at fr.finaxys.tutorials.hadoop.AtomGenerate.main(AtomGenerate.java:81)
```

We need a clearer message for the user.

**Comment by raphaelhamonnais** [comment]
@BittnerPierre Fix ok --> close issue ?

**Comment by BittnerPierre** [comment]
Did you implement unit test?

**Comment by BittnerPierre** [comment]
public boolean check_hadoopConfCore_fileExists() {
 +			return new File(hadoopConfCore).isFile();
 +	}
 +	public boolean check_hadoopConfHdfs_fileExists() {
 +		return new File(hadoopConfHdfs).isFile();
 +	}
 +	public boolean check_hbaseConfHbase_fileExists() {
 +		return new File(hbaseConfHbase).isFile();
 +	}

This does not respond to java standard code convention.

**Comment by raphaelhamonnais** [comment]
@BittnerPierre -> what do you think of this approach ?

Manual tests with the new commit : no error when the path to the `hbase-site.xml` is correct.

Error thrown and catch in the main if the path is incorrect : 

```
.......
15:01:42.414 [main] ERROR fr.finaxys.tutorials.hadoop.AtomGenerate - Error when creating injectors in AtomGenerate.main()
fr.finaxys.tutorials.utils.HadoopTutorialException: Path to hbase config file in properties.txt is incorrect !
	at fr.finaxys.tutorials.utils.hbase.AtomHBaseHelper.createHbaseConfiguration(AtomHBaseHelper.java:291) ~[classes/:?]
	at fr.finaxys.tutorials.utils.hbase.AtomHBaseHelper.<init>(AtomHBaseHelper.java:86) ~[classes/:?]
	at fr.finaxys.tutorials.utils.hbase.SimpleHBaseInjector.<init>(SimpleHBaseInjector.java:32) ~[classes/:?]
	at fr.finaxys.tutorials.hadoop.AtomGenerate.initInjectors(AtomGenerate.java:138) ~[classes/:?]
	at fr.finaxys.tutorials.hadoop.AtomGenerate.main(AtomGenerate.java:55) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]

Process finished with exit code 0
```


Error obtained by setting (in the file `properties.txt`) an incorrect path for `hbase-site.xml` file and running `AtomGenerate.main()` with all `simul.output.*` set to false except `simul.output.hbase` which is set to true.


Currently working on how to implement unit tests.

**Comment by raphaelhamonnais** [comment]
### Thoughts on how to unit test that error is thrown correctly

`AtomHBaseHelper` being an abstract class, I think it's better to test `AtomHBaseHelper. createHbaseConfiguration` method via it's subclass `SimpleHBaseInjector`.

And there is a test file already testing this class : `SimpleHBaseInjectorTest`.

##### Problem (I think) : 
Before each test, the HBase configurations are set using `SimpleHBaseInjector.setHbaseConfiguration` method with `HBaseTestingUtility.getConfiguration()` as argument (instance of `org.apache.hadoop.conf.Configuration`).

Furthermore, the `SimpleHBaseInjector` instance used in the test is created with the empty constructor :

```java
private SimpleHBaseInjector injector = new SimpleHBaseInjector();
```
So there is no call to the superclass constructor, that is to say the `AtomHBaseHelper` constructor that calls the method `createHbaseConfiguration(AtomConfiguration atomConf)`.
Or it's in the `AtomConfiguration` parameter that there is the path to the HBase configuration file and this is this path that we need to test : if the file exists, no exception thrown. But if the file does not exist, then a `HadoopTutorialException` must be thrown.


And finally, how can we mock a file system in the test environment to test existing and non existing file ?

**Comment by raphaelhamonnais** [comment]
Note for later : 

>And finally, how can we mock a file system in the test environment to test existing and non existing file ?

Maybe we don't need to mock a file system and directly use `java.io.file.exists()` to test if the file exists.
